version: "3.9"

services:
  api:
    image: herevemarket-backend:latest
    container_name: herevemarket-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /var/lib/herevemarket/uploads:/app/public/uploads
